### ISSUE TITLE
Cannot get AnyChart to work on Elastic Beanstalk / AWS

### ISSUE THREAD

**Issue by martymix** [AnyChart/AnyChart-NodeJS#19]
Tried a bunch of things but can't seem to get AnyChart to generate a file on AWS. I am using the "Quick Start" code. 

I am able to get this working locally without issue.

In the logs, I have an error of:

Warning! Please install rsvglib utility. (https://github.com/AnyChart/AnyChart-NodeJS)
Error: Stream yields empty buffer
    at Socket.<anonymous> (/var/app/current/node_modules/gm/lib/command.js:57:17)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:978:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

Which seem to point to an ImageMagick installation issue, however I am trying a packages.config file with:

packages:
  yum:
    ImageMagick: []
    librsvg2-dev: []
    librsvg2-bin: []

seems like I can get ImageMagick to install if I remove the librsvg2 packages, but the other two packages are not found.
(Return code: 1 Output: Yum does not have librsvg2-dev available for installation)

In addition, just to see, i was able to install the "GraphicsMagick" module and was able to successfully write an image in AWS. 

Any thoughts or any success on getting AnyChart to work on Elastic Beanstalk?

Thanks!

**Comment by Shestac92** [comment]
@martymix 
Unfortunately, we didn't test the module on AWS. But we met the same problem on several OS versions. With high probability, the problem comes from dependencies, compatibility of versions. Not all imageMagick versions work properly.
We recommend `7.0.8-11_1` version if it is available.
More details about this issue you can find [here](https://github.com/AnyChart/AnyChart-NodeJS/issues/12#issuecomment-421885023) and [here](https://github.com/AnyChart/AnyChart-NodeJS/issues/17#issuecomment-461281850).
